### ISSUE TITLE
"2D slider"

### ISSUE THREAD

**Issue by Sohalt** [basic-web-components/basic-web-components#12]
I'd like to suggest adding a slider, that allows for control of the granularity of movement in the direction of the slider (parallel to the slider), by moving in the orthogonal direction.
So a horizontally oriented slider would adjust a value when moving the mouse in a horizontal direction and moving the mouse vertically would determine by how much horizontal movement affects the value.
Moving away from the slider (vertically) makes horizontal movements more sensitive/increases the granularity, allowing for more precision.
In other words, the distance of the mouse from the slider (vertical movement) is inversely proportional to the rate at which horizontal movement modifies the value.

To specify an exact value one would then click roughly in the area where the value lies, making rough adjustments and then moving away with the mouse from the slider to increase precision and make final adjustments.

___

This idea is roughly related to the sliders used in GIMP for modifying tool parameters, e.g. brush size or opacity. http://gui.gimp.org/index.php/Tool_Options_widgets#GimpSpinScale
Here the slider is divided horizontally into two differently functioning regions (indicated by the cursor shape changing) where in one (the upper) region the slider follows the mouse 1:1 (the "handle" so to speak always is directly under the cursor) and in the other (lower) region the slider moves "slower" with regards to the mouse, therefore allowing for increased precision and fine tuning.
The controls can be seen in the top two images in [this](http://gimpforums.com/thread-brush-size-in-2-8?pid=16682#pid16682) post although they are probably best experienced live (GIMP is free software, so everybody can try it)

**Comment by JanMiksovsky** [comment]
Can you add this to the new [Desired Components](https://github.com/basic-web-components/basic-web-components/wiki/Desired-Components) page? Let's track this idea there.

**Comment by Sohalt** [comment]
Not sure it would be a fit, because I'm not aware of any application that uses the component in the form I envision. I can add the variation that is used in GIMP though.

**Comment by JanMiksovsky** [comment]
Please add the GIMP variation if you'd like. I'll close this out as an active issue.
