### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by joeblew99** [basic-web-components/basic-web-components#23]
but project stopped with commits ? Dead and buried ? Better to just use Polymer instead ?

**Comment by robbear** [comment]
@joeblew99 On the contrary! The basic-web-components project is alive and well, and we will have more news coming very soon. The current slow down in commits is due in part to some long-planned summer vacations, as well as some strategic planning for moving forward as the Web Components spec solidifies in browser implementations. Stay tuned.

**Comment by JanMiksovsky** [comment]
@joeblew99 We're currently focusing on two things:

1. Adding support for Shadow DOM v1 and Custom Elements v1. You can follow along on the `web-components-v1` branch.
2. Working with another large components project with the hope of ultimately unifying our efforts. This is a significant initiative, so it's soaking up a substantial amount of our time.

I hope that helps. Please let us know if you have other thoughts!
