### ISSUE TITLE
basic-carousel: binding to selectedIndex

### ISSUE THREAD

**Issue by Jamtis** [basic-web-components/basic-web-components#5]
Hi,

I use the [`basic-carousel`](https://basic-web-components.github.io/basic-web-components/docs/#basic-carousel).
It works just fine standalone but now I try to interact with it somehow.

I tried setting the `selectedIndex` attribute but I figured that the `selectedIndex` property is not mapped to it's attribute...

I personally would like to use

```
<template is="dom-bind">
<paper-tabs selected="{{selected}}"></paper-tabs>
<basic-carousel selectedIndex="{{selected}}"></basic-carousel>
</template>
```
 analogly to [`iron-pages`](https://elements.polymer-project.org/elements/iron-pages).
```
<template is="dom-bind">
<paper-tabs selected="{{selected}}"></paper-tabs>
<iron-pages selected="{{selected}}"></iron-pages>
</template>
```

So my proposal is to consider [`IronSelectableBehavior`](https://elements.polymer-project.org/elements/iron-selector?active=Polymer.IronSelectableBehavior).

What do you think?

Is there an easy way to bind `selectedIndex`?

**Comment by JanMiksovsky** [comment]
@Jamtis: Thanks for the report. This used to work, but perhaps was broken during the transition to Polymer 0.8. I'll investigate.

**Comment by Jamtis** [comment]
Any progress?

**Comment by JanMiksovsky** [comment]
@Jamtis Looking at this now, sorry for the delay. This may be more complex than I'd thought, but I'm hoping to have something for you to try in the next day or so.

**Comment by JanMiksovsky** [comment]
Okay, so that wasn't so bad. The master branch has an updated version of basic-carousel and basic-carousel-fit that expose bindable selectedIndex and selectedItem properties.

Some notes:
* In Polymer 1.0, you need to use the hyphenated property names when binding:
```
<basic-carousel selected-index="{{selected}}"></basic-carousel>
```
* If you use any of the wrapper components like basic-arrow-direction or basic-page-dots (as shown in the basic-carousel demo), you'll want to bind to the `selected-index` property on the outermost wrapper element, since that's the one that will raise the property change event.

Please give this a try and let me know if you run into any issues. You're the first person to try this, so I'm happy to help debug any problems you run into.

**Comment by Jamtis** [comment]
Thanks for the support.
I really appreciate it:)

I'll test it later on today and report the results.

**Comment by Jamtis** [comment]
So I tested the binding and it works one-way.

```
<template is="dom-bind">
<paper-tabs selected="{{selected}}"></paper-tabs>
<basic-carousel selected-index="{{selected}}"></basic-carousel>
</template>
```

When I click the tabs the carousel children change but when I change the carousel selection via UI the tabs are not affected.
I guess that is somehow related to [Two way binding](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#property-notification).

Also I can't assign `selectedIndex` to the element via JS.
When I change the carousel elements `carousel.selectedIndex` returns `-1`.

**Comment by JanMiksovsky** [comment]
@Jamtis Ugh, this was my fault — when I added binding support to the carousel in the master basic-web-components source repo, I'd failed to actually push the updated release to the individual component repos (e.g., basic-carousel) which Bower uses.

I just pushed these changes, and the problem appears to be fixed. I've built a paper-tabs + basic-carousel test and confirmed that binding works in both directions. Additionally, you can programmatically update the index by setting the appropriate property on either the template or the basic-carousel instance.

Please give this another try, and my apologies for wasting your time checking a component version that hadn't actually been updated.

Aside: I'd been meaning to try a tabs + carousel demo at some point. It's pretty cool! Thanks for trying that.

**Comment by Jamtis** [comment]
I updated bower but I get the same result.

Are you sure you've updated the repo?

Latest changes I see are from [June 9](https://github.com/basic-web-components/basic-carousel/network).

**Comment by JanMiksovsky** [comment]
This is just on #master — it hasn't been released yet.

**Comment by Jamtis** [comment]
Okay, I'm quite new to this kind of deployment.

Where is the code you updated?

Does it take a while for deployment script to run or bower to update?

**Comment by JanMiksovsky** [comment]
You can update your bower.json to reference the master branch:

```
{
  "name": "carousel-with-tabs",
  "dependencies": {
    "basic-carousel": "basic-web-components/basic-carousel#master",
    "paper-tabs": "PolymerElements/paper-tabs#^1.0.0",
    "polymer": "Polymer/polymer#^1.0.5"
  }
}
```

**Comment by Jamtis** [comment]
I get the concept :)
I'm testing right now.

**Comment by Jamtis** [comment]
Bummer...
I updated to master but I still get the same results.

`carousel.selectedIndex` doesn't match the actual index and binding is still one-way.

Do you have any more ideas or shall I open a repo for further investigation in cooperation?

**Comment by JanMiksovsky** [comment]
Weird, I'm not sure why this isn't working for you yet.

I've posted my own demo of this working: https://github.com/JanMiksovsky/carousel-with-tabs.
You can see this running at http://janmiksovsky.github.io/carousel-with-tabs.
I've cloned this on a separate machine, and confirmed it works there.

Can you give that a try, and let me know if you spot any differences in config, etc., from your own project? I'd really like to get this working for you.

**Comment by Jamtis** [comment]
Well you are right.
Your example works like a charm in my environment.

But my exact case looks like this:

```
<template is="dom-bind">
    <paper-tabs selected="{{selected}}">
        <paper-tab>Image 1</paper-tab>
        <paper-tab>Image 2</paper-tab>
    </paper-tabs>
    <basic-arrow-direction target="child" class="overlay" aria-label="Images" role="listbox" style="height: 200px;">
        <basic-page-dots target="child">
            <basic-carousel selected-index="{{selected}}">
                <img src="http://hosting.component.kitchen/resources/images/image1.jpg" alt="Lake">
                <img src="http://hosting.component.kitchen/resources/images/image2.jpg" alt="Horses">
            </basic-carousel>
        </basic-page-dots>
    </basic-arrow-direction>
</template>
```

It does not work for me.
I didn't bring up the whole code in the first place because I thought the module are independent.
But somehow they interfere in a way that breaks this code.

Can you confirm that it does not work?

**Comment by JanMiksovsky** [comment]
It looks like you're binding to the inner basic-carousel. It cooperates with the wrapper components basic-arrow-direction and basic-page-dots to avoid raising multiple property change events; the outermost component in that group will raise the property change notification. This is the situation I noted in a bullet above. (I need to investigate whether there's a way for an inner component to detect that someone's trying to bind to it, and have it raise the event in that case.)

In this case, please try binding to selected-index on the basic-arrow-direction component.

**Comment by Jamtis** [comment]
Binding `selected-index` to `basic-arrow-direction` does not work.

Also I find it personally inconvenient to bind the index to the `basic-arrow-direction` which originally belongs to `basic-carousel`.

**Comment by JanMiksovsky** [comment]
I've updated both the [sample repo](https://github.com/JanMiksovsky/carousel-with-tabs) and the [live demo](http://janmiksovsky.github.io/carousel-with-tabs) to include basic-arrow-direction and basic-page-dots. It works as expected — are you seeing different behavior?

I agree that it's odd to have to change what you're binding to, but these components are designed to work as a unit. If you wrap basic-carousel with basic-arrow-direction and basic-page-dots, all three share the same underlying index property. That creates challenges in generating the property change event that Polymer relies on for data binding. As I said, I can investigate if there's a way to redesign things so that, potentially, any of the components could generate the property change event.

**Comment by Jamtis** [comment]
Works fine now.

I changed nothing.. I guess there were some caching issues.

I'd like to thank you for your quite dedicated support. :+1:

**Comment by JanMiksovsky** [comment]
Glad to hear it's working now, and happy to have helped out.

We're planning out the next few months' of work on components, so if you have additional thoughts on the components, let us know. I've already noted the interest in being able to bind to properties like selectedIndex on inner components, such as basic-carousel in this example.

**Comment by Jamtis** [comment]
I will!
