### ISSUE TITLE
Arrow buttons leak events

### ISSUE THREAD

**Issue by Jamtis** [basic-web-components/basic-web-components#7]
When you click the arrow buttons the body element receives events.

I assume this is not the intended behavior.

Here's a [jsbin](http://jsbin.com/fezinojoze/2/edit?html,output).

In previous versions of basic-elements this behavior did not appear.

**Comment by JanMiksovsky** [comment]
@Jamtis Thanks for the report. I'll investigate, but I wanted to mention that it will be next week before I will have a chance to look at this.

**Comment by Jamtis** [comment]
No problem. Maybe I find the time to fix it myself and make a PR.

**Comment by Jamtis** [comment]
I updated the [jsbin](http://jsbin.com/xosakoregi/1/edit?html,output).

`event.stopPropagation()` prevents the events from leaking through.

**Comment by Jamtis** [comment]
Also I would suggest to switch to the tap event instead of click.

**Comment by JanMiksovsky** [comment]
I've updated basic-arrow-direction with a fix for this. The new behavior is: if an arrow buttons handles the click, it stops propagation. However, if the arrow button doesn't handle the click, the event propagates. This situation comes up when the carousel is on the first (or last) item and the user clicks the left (or right) button.

While the tap event is appealing, I'm finding it a bit too magic for use just yet. Case in point: I tried using the tap event here, and it didn't work as expected. I'll monitor progress on that event, and will keep looking for an opportunity to use it.

This fix is on the master branch of the consolidated basic-web-components repository. It will go out in the next release, which should be 0.6.3, at which point it will make its way to the Bower-compatible basic-arrow-direction repository.

**Comment by Jamtis** [comment]
Nice that it's fixed.

About the tap event: That's exactly what I'd do too.

Big :+1: for your great support.

**Comment by JanMiksovsky** [comment]
@Jamtis De nada — you make these components better with your issues and feedback.

Since this sounds like an acceptable resolution, I'm going to mark this as closed.

BTW, we're planning out our next investments in this component set, and would love your feedback. If there are areas where you'd like to see us invest — more improvements to basic-carousel, or new components, or anything else — then send your thoughts to me at jan@component.kitchen. Thanks.

**Comment by JanMiksovsky** [comment]
This fix has now [been released](https://github.com/basic-web-components/basic-web-components/releases/tag/v0.6.3).
