### ISSUE TITLE
Basic-carousel: behavior on small images

### ISSUE THREAD

**Issue by Jamtis** [basic-web-components/basic-web-components#9]
I recognized strange behavior when using `basic-carousel` with small images.

https://jsfiddle.net/jamtis/zs86psat/

I changed `#slidingContainer width: 100%;` and `#spreadContainer.basic-spread-items > * object-fit: scale-down;`.

This way small images stay centered and don't scale up which - I think - is the most convenient behavior.

**Comment by JanMiksovsky** [comment]
Hmm, this is a really interesting issue.

First, thanks for pointing out the `scale-down` value for object-fit — I hadn't know about that value.

I'm not sure there's a single answer here. In many (most?) situations, you do want the image to scale up to fit the carousel. When viewing the basic-carousel demo on a desktop device, for example, it's reasonable to scale the images up, because they still look good. But your example raises cases where the images are too small to scale up.

One solution would be to define a CSS variable in basic-spread-items, which is responsible for scaling the contents of a basic-carousel. Alternatively, given that this is a common situation, we could expose a property on basic-spread-items and basic-carousel that choose the scaling behavior.

I need to give this a bit more thought. Thanks for raising this point.

**Comment by Jamtis** [comment]
I think CSS variables are well suited for this case.

**Comment by Jamtis** [comment]
Do we agree on `#slidingContainer { width: 100%; }`?

**Comment by JanMiksovsky** [comment]
I'm working on a fix for this to introduce a CSS variable, --basic-item-object-fit, that will apply to items inside of basic-spread-items, and therefore basic-carousel. Some unrelated issues are preventing me from fully testing this, but I'll let you know when that's resolved and this is on master.

I'm not sure that it's necessary to also set an explicit width on `#slidingContainer`. That element sits inside of an element with `display: flex`, so it should already have its width effectively set to 100%. I want to confirm this in all the browsers, though, and as I said, I'm having some issues doing that just now. If you have any configuration information to share that might help me track down the need for an explicit width on `#slidingContainer`, though, please let me know.

**Comment by Jamtis** [comment]
The usual suspects Edge and IE need this.

**Comment by Jamtis** [comment]
I wouldn't care about IE that much but Edge is somehow relevant.

**Comment by JanMiksovsky** [comment]
Huh. I can't figure out what IE/Edge need that `width: 100%`, but it definitely has an effect. Thanks for pointing that out.

I've checked in that IE/Edge fix, as well as the new `--basic-item-object-fit` CSS variable. You can try those things on the master branch now, or wait until v0.6.4 is release sometime, probably early December.

**Comment by Jamtis** [comment]
I'll check it out tomorrow.

**Comment by Jamtis** [comment]
I don't understand why https://jsfiddle.net/zs86psat/5/ work in Edge but https://janmiksovsky.github.io/carousel-with-tabs/ doesn't.
I get the exact same CSS properties/values...

Why does `#slidingContainer` on carousel-with-tabs not scale to maximum width?

**Comment by Jamtis** [comment]
@JanMiksovsky Can you confirm this behavior?

**Comment by JanMiksovsky** [comment]
That carousel-with-tabs demo is still using an old release of Basic Web Components. For one thing, that demo isn't an official part of the BWC project, so I don't normally keep that up to date. Separately, we currently break the consolidated BWC repository into individual repos for Bower distribution. That process is unfortunately slow and cumbersome, so we only do that when we make an official BWC release. We still haven't released v0.6.4 yet, so the individual repos like basic-sliding-viewport (which owns `#slidingContainer`) are still on v0.6.3.

When we release 0.6.4, I can double-check to make sure the carousel-with-tabs demo works as expected in Edge. As I said, I am hoping to release 0.6.4 in December.

**Comment by Jamtis** [comment]
I figured out why `#slidingContainer` needs `width: 100%`.
It's `position: absolute`!
This prevents `flex: 1` from applying.
+1 for splitting into bower distros.

**Comment by JanMiksovsky** [comment]
Version 0.6.4 has now been released. The carousel-with-tabs demo now works in Edge.
